/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_pech_pradeau_dupuy;

/**
 *
 * @author Raphaël
 */
import javax.swing.Timer;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.Point;
public class FenetrePrincipale extends javax.swing.JFrame {
    Echiquier echiquier;
    private int compteur;
    int score;
    int nbSec;
    Timer chrono;
    int partie;
    int partie1;
    int jok;
    int niv1;
    boolean test;
   
    /**
     * Creates new form FenetrePrincipale
     */
    
    public FenetrePrincipale() {
    initComponents();
    }
    
    /**
     *
     * @param partie
     * @param niv
     * initialise une partie, avec ou non un chronometre selon le mode de jeu
     */
    public FenetrePrincipale(int partie, int niv) {
        initComponents();
        partie1 = partie;
        test = true;
        compteur = 0;
        score = 0;
        jok = 1;
        int taille = 10;
        niv1=niv;
        this.echiquier= new Echiquier(taille);
        PanelEchiquier.setLayout(new GridLayout(taille, taille));
        
        for (int i=0; i < taille; i++) {
            for (int j=0; j < taille; j++ ) {
                CaseGraphique bouton_cellule = new CaseGraphique( echiquier.grid[i][j], 1440/taille,1080/taille,i ,j);
                bouton_cellule.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        // Appeler votre fonction ici
                        onCaseClicked(bouton_cellule);
                    }
                });
                PanelEchiquier.add(bouton_cellule);
            }
        }
        depart();
        
       
        if (partie==1){
            chronobtn.setVisible(false);
        }
        if (partie == 2){
            
         nbSec = niv;
        ActionListener tache_recurrente = new ActionListener() {
            public void actionPerformed(ActionEvent e1) {
                
                nbSec--;
                System.out.println(nbSec);
                chronobtn.setText(nbSec + "");
                if (nbSec == 0){
                    chrono.stop();
                    if (test==true){
                    fenetredefaite f2 = new fenetredefaite();
                    f2.setVisible(true);
                    setVisible(false);
                }}
            }
            ;
        };
        
        
        /* instanciation du timer */
        chrono = new Timer(1000, tache_recurrente);
        
        chrono.start();}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEchiquier = new javax.swing.JPanel();
        menuP = new javax.swing.JButton();
        quitter = new javax.swing.JButton();
        scorebtn = new javax.swing.JButton();
        joker = new javax.swing.JButton();
        chronobtn = new javax.swing.JButton();
        photoFond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelEchiquier.setBackground(new java.awt.Color(255, 255, 255));
        PanelEchiquier.setMaximumSize(new java.awt.Dimension(1440, 1080));
        PanelEchiquier.setPreferredSize(new java.awt.Dimension(510, 510));

        javax.swing.GroupLayout PanelEchiquierLayout = new javax.swing.GroupLayout(PanelEchiquier);
        PanelEchiquier.setLayout(PanelEchiquierLayout);
        PanelEchiquierLayout.setHorizontalGroup(
            PanelEchiquierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        PanelEchiquierLayout.setVerticalGroup(
            PanelEchiquierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        getContentPane().add(PanelEchiquier, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 510, 440));

        menuP.setBackground(new java.awt.Color(220, 218, 181));
        menuP.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        menuP.setText("MENU PRINCIPAL");
        menuP.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(147, 78, 10)));
        menuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPActionPerformed(evt);
            }
        });
        getContentPane().add(menuP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        quitter.setBackground(new java.awt.Color(220, 218, 181));
        quitter.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        quitter.setText("QUITTER");
        quitter.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(147, 78, 10)));
        quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterActionPerformed(evt);
            }
        });
        getContentPane().add(quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 610, 129, -1));

        scorebtn.setBackground(new java.awt.Color(220, 218, 181));
        scorebtn.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        scorebtn.setText("SCORE : 0");
        scorebtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(147, 78, 10)));
        getContentPane().add(scorebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 100, 27));

        joker.setBackground(new java.awt.Color(220, 218, 181));
        joker.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        joker.setText("Relance");
        joker.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(147, 78, 10)));
        joker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jokerActionPerformed(evt);
            }
        });
        getContentPane().add(joker, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 323, 100, 30));

        chronobtn.setBackground(new java.awt.Color(220, 218, 181));
        chronobtn.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        chronobtn.setText("jButton1");
        chronobtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(147, 78, 10)));
        getContentPane().add(chronobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 37, 34));

        photoFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background2.png"))); // NOI18N
        getContentPane().add(photoFond, new org.netbeans.lib.awtextra.AbsoluteConstraints(-530, 20, 1880, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jokerActionPerformed
        echiquier.eteindreTout();
        depart();
        joker.setVisible(false);
        repaint();
        jok--;
    }//GEN-LAST:event_jokerActionPerformed

    private void quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterActionPerformed
     System.exit(0);   // TODO add your handling code here:
    }//GEN-LAST:event_quitterActionPerformed

    private void menuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPActionPerformed
     Fenetrebvn f4 = new Fenetrebvn ();
     f4.setVisible(true);
     setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_menuPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }}
        );
    }
    
    private void relance(){
        int a = echiquier.nombrelum();
        if (a==0){
            depart();
        }
    }
    private void depart(){
            echiquier.parcours();
            if (jok==1){
                joker.setVisible(true);
            }
            }
            
private void onCaseClicked(CaseGraphique caseCliquee) {

    int newligne = caseCliquee.getLigne();
    int newcolonne = caseCliquee.getColonne();
    int ligne = echiquier.CoordCavalierX();
    int colonne = echiquier.CoordCavalierY();
    joker.setVisible(false);
    echiquier.verif(ligne, colonne, newligne, newcolonne);
   if (echiquier.verif(ligne, colonne, newligne, newcolonne)==true && (echiquier.grid[newligne][newcolonne].getEtat()==2)){

       echiquier.grid[ligne][colonne].setEtat(1);
        echiquier.grid[newligne][newcolonne].setEtat(3);

   compteur++;
       int a = echiquier.nombrelum();
        if (a==0 && compteur == 10){
                compteur = 0;
                score ++;
                scorebtn.setText("Score : " + score);
                if (partie1==2 && score==3){
                    test = false;
                    fenetreVictoire f3 = new fenetreVictoire(niv1 - nbSec);
                    f3.setVisible(true);
                    setVisible(false);
                }
                depart();
        }
        if (echiquier.verifMouvementsPossibles(newligne, newcolonne)==false && a!=0 ){
           
            fenetredefaite f2 = new fenetredefaite(score);
          f2.setVisible(true);
          setVisible(false);
          depart();
          compteur = 0;
       }
   
        // relance();
    repaint();
   }
   
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEchiquier;
    private javax.swing.JButton chronobtn;
    private javax.swing.JButton joker;
    private javax.swing.JButton menuP;
    private javax.swing.JLabel photoFond;
    private javax.swing.JButton quitter;
    private javax.swing.JButton scorebtn;
    // End of variables declaration//GEN-END:variables
}

