/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_pech_pradeau_dupuy;

/**
 *
 * @author Camille
 */
public class fenetredefaite extends javax.swing.JFrame {

    /**
     * Creates new form fenetredefaite
     * @param score
     */
    public fenetredefaite(int score) {
        initComponents();

        perduscorebtn.setText("Score : " + score );
        
    }
    public fenetredefaite() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menubtn = new javax.swing.JButton();
        perduscorebtn = new javax.swing.JButton();
        quitter = new javax.swing.JButton();
        photoFond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menubtn.setBackground(new java.awt.Color(220, 218, 181));
        menubtn.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        menubtn.setText("MENU PRINCIPAL");
        menubtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(147, 78, 10)));
        menubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubtnActionPerformed(evt);
            }
        });
        getContentPane().add(menubtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 140, 30));

        perduscorebtn.setBackground(new java.awt.Color(220, 218, 181));
        perduscorebtn.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        perduscorebtn.setText("SCORE");
        perduscorebtn.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(147, 78, 10)));
        getContentPane().add(perduscorebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 140, 50));

        quitter.setBackground(new java.awt.Color(220, 218, 181));
        quitter.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        quitter.setText("QUITTER");
        quitter.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(147, 78, 10)));
        quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterActionPerformed(evt);
            }
        });
        getContentPane().add(quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 140, 30));

        photoFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/perdu.png"))); // NOI18N
        photoFond.setText("jLabel1");
        photoFond.setPreferredSize(new java.awt.Dimension(350, 680));
        getContentPane().add(photoFond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 980));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubtnActionPerformed
        Fenetrebvn fenetre = new Fenetrebvn();
        fenetre.setVisible(true);
        setVisible(false);
    // TODO add your handling code here:
    }//GEN-LAST:event_menubtnActionPerformed

    private void quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterActionPerformed
       System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_quitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetredefaite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetredefaite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetredefaite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetredefaite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetredefaite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton menubtn;
    private javax.swing.JButton perduscorebtn;
    private javax.swing.JLabel photoFond;
    private javax.swing.JButton quitter;
    // End of variables declaration//GEN-END:variables
}
